[package]
name = "iotop"
description = "A Rust implementation of iotop"
license = "MIT"
version = "0.1.0"
edition = "2021"

[lib]
name = "iotop"
path = "src/lib.rs"

[[bin]]
name = "iotop"
path = "src/main.rs"

[dependencies]
argh = "0.1"
nix = { version = "0.29", features = ["process", "user"] }
anyhow = { version = "1.0", features = ["std"] }
crossterm = "0.28"
libc = { version = "0.2", features = ["std"] }
linux-taskstats = { version = "0.7", features = ["executable"] }

[patch.crates-io]
linux-taskstats = { path = "patches/linux-taskstats" }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
